package CoreJava.DAO;

import java.util.List;

import CoreJava.Models.Attending;
import CoreJava.Models.Course;
import CoreJava.Models.Student;
import CoreJava.systemInterfaces.AttendingDAOI;

public class AttendingDAO implements AttendingDAOI{

	
	public int registerStudentToCourse(Student student, Course course) {
		/*This method takes as a parameter a Student and a Course object. 
		If the student’s GPA id greater or equal to the minimum GPA of 
		the course then the student is allow to register to the course. 
		If not, then throw the StudentRegistrationException with a custom 
		massage such as “\nDid not meet the minimum GPA requirement\nRegistration Denied”. 
		Since you are creating a new record in the database, 
		return the primary key auto-generated by the database.*/
	}


	public List<Attending> getStudentCourse(int student_id) {
	/*	This method takes as a parameter a int student_id and would query
		the database for all the courses a student is register base on the Id*/
		
	}

	
	
	
	
	
}
